spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.79.130
    port: 6379
  session:
    store-type: redis
    timeout: 30m
server:
  port: 20000