spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: true
  redis:
    host: 192.168.79.130
    port: 6379
  session:
    store-type: redis
server:
  port: 13000